### ISSUE TITLE
How can I get my wallet address from my Mnemonic?

### ISSUE THREAD

**Issue by dopi4720** [continuation-team/TonSdk.NET#102]
I have create Mnemonic like that:

`Mnemonic mnemonic = new Mnemonic(new string[] { "some", "word", "here" });`
`string PublicKeyString = BitConverter.ToString(mnemonic.Keys.PublicKey).Replace("-", "").ToLower();`
`string PrivateKeyString = BitConverter.ToString(mnemonic.Keys.PrivateKey).Replace("-", "").ToLower();`

But I don't know how to export my wallet address. Please tell me how to do this, please.
Many thanks to support team

**Comment by purpleguy99** [comment]
https://docs.tonsdk.net/user-manual/contracts/wallet/wallet-v3-v4
