### ISSUE TITLE
Invalid coins value

### ISSUE THREAD

**Issue by Zeddex** [continuation-team/TonSdk.NET#106]
If I set coins amount in double format it throws me an error "Invalid Coins value".

For example here or while creating transfer message:
```
decimal tonAmount = 0.1d;

Cell swapToJettonBody = DeDustNativeVault.CreateSwapBody(new DeDustNativeSwapOptions()
{
    PoolAddress = pool.Address,
    Amount = new Coins(tonAmount)
});
```

But if the amount is in string format, it works good.

**Comment by purpleguy99** [comment]
fixed in #108
