### ISSUE TITLE
LITECLIENT GetBlockTransactions returns incorrect Tx Hash

### ISSUE THREAD

**Issue by jamescarter-le** [continuation-team/TonSdk.NET#111]
Calling `GetBlockTransactions` against the lite-server, returns Base64 transaction hashes, which have been converted to lowercase, meaning the data is lost and represents nothing.

![image](https://github.com/continuation-team/TonSdk.NET/assets/1643692/ad4bab7d-f47e-41c2-bd9b-427ad9fe6998)

`hbofaj6rcnaliys8l8pit2fchauvgdyfv4zimnngvys=`
Should be
`hBOFaj6RcnaLiyS8l8piT2FcHAuvGDYfV4ZImnNGvys=`

**Comment by purpleguy99** [comment]
will check it

**Comment by purpleguy99** [comment]
fixed in https://github.com/continuation-team/TonSdk.NET/pull/112/commits/e3755d5916e220541608e66757ecd21d4e660b27
