### ISSUE TITLE
Wallet base64 address incorect

### ISSUE THREAD

**Issue by vsolovev** [continuation-team/TonSdk.NET#118]
Step 1) take raw address string
Step 2) create new instance of Address
Step 3) call ToString with base64 type

Expecting result: correct base64 address string returned
Actual: 1 first and 3 last letters in base64-form of address changed for some reason

![image](https://github.com/user-attachments/assets/079729ef-c05e-421f-a31d-60d6b600af36)

As you can see, raw strings are equal but base64 forms differs

**Comment by purpleguy99** [comment]
just use different formatings, https://docs.tonsdk.net/user-manual/core/address

**Comment by purpleguy99** [comment]
```// ex, 0:83...a8
string raw = address.ToString(AddressType.Raw);

// ex, EQC...2N
string base64Bounceable = address.ToString(AddressType.Base64, new AddressStringifyOptions(true, false, false);

// ex, UQC...BI
string base64NonBounceable = address.ToString(AddressType.Base64, new AddressStringifyOptions(false, false, false);

// ex, kQC...YH
string base64BounceableTestOnly = address.ToString(AddressType.Base64, new AddressStringifyOptions(true, true, false);

// ex, 0QC...vC
string base64NonBounceableTestOnly = address.ToString(AddressType.Base64, new AddressStringifyOptions(false, true, false);```

**Comment by vsolovev** [comment]
Got it, thanks
