### ISSUE TITLE
I used your demo code to send Ton, but always get 500 error

### ISSUE THREAD

**Issue by ZhangYiQiu** [continuation-team/TonSdk.NET#12]
![image](https://github.com/continuation-team/TonSdk.NET/assets/22910338/b9e8778a-5149-498c-ba24-d560ae04d35c)
LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted
Cannot run message on account: inbound external message rejected by transaction 892283FFF6000124E96BCDA3258A4E0119CE47F2C3D909F95D3E633D5CE37535:
exitcode=9, steps=19, gas_used=0
VM Log (truncated):
...ecute PUSHCONT x71B0ED44D0D31FD31F31D70BFFE304
execute IFJMP
execute INC
execute THROWIF 32
execute PUSHPOW2 9
execute LDSLICEX
execute DUP
execute LDU 32
handling exception code 9: cell underflow
default exception handler, terminating vm with exit code 9

**Comment by pyAndr3w** [comment]
@ZhangYiQiu, if you use a wallet other than preprocessedV2, then you need to remove `true` from `.Sign`

should be just `.Sign(mnemonic.Keys.PrivateKey)`

**Comment by ZhangYiQiu** [comment]
> @ZhangYiQiu, if you use a wallet other than preprocessedV2, then you need to remove `true` from `.Sign`
> 
> should be just `.Sign(mnemonic.Keys.PrivateKey)`

thank you very much
