### ISSUE TITLE
How to convert Coins Class to decimal? Only convert to string and then to decimal?

### ISSUE THREAD

**Issue by ZhangYiQiu** [continuation-team/TonSdk.NET#13]
The amount is usually stored in decimal, but with this sdk I can only get the Coins object, the way I'm doing it now is to convert the Coins to string and then convert the string to decimal. 

![image](https://github.com/continuation-team/TonSdk.NET/assets/22910338/c44a155c-32a3-4694-95d7-d5ff8896f03e)

This involves multiple type conversions.
**Is there a better way to do it?**

**Comment by purpleguy99** [comment]
Hello, we will upgrade our SDK that users can get coins in numeric types, thank you for detecting this issue!

**Comment by ZhangYiQiu** [comment]
> Hello, we will upgrade our SDK that users can get coins in numeric types, thank you for detecting this issue!

thanks

**Comment by artmon** [comment]
I do this now: 
`(decimal)coins.ToBigInt()`

**Comment by ZhangYiQiu** [comment]
> I do this now: 
> 
> `(decimal)coins.ToBigInt()`
> 
> 

You're ignoring precision.
For example, `1.23`, you'll only get `1`

**Comment by purpleguy99** [comment]
We are added support to get decimal value. Check it #21.
