### ISSUE TITLE
read the comment of a jetton transfer transaction

### ISSUE THREAD

**Issue by r4mze5** [continuation-team/TonSdk.NET#25]
Hello
How can I read the comment of a jetton transfer transaction? And check the status, successful or not?

**Comment by purpleguy99** [comment]
We will add support of this feature in nearest updates.

**Comment by purpleguy99** [comment]
I think now, it doesnt exists any NFT and Jetton SDK tools. We can add this feature in nearest future, if it will topped by our users. At the moment, you can parse transaction payload data using cellslice and read the data according to TL-B Schemes.
