### ISSUE TITLE
Cant get Ton transaction

### ISSUE THREAD

**Issue by Maxim055** [continuation-team/TonSdk.NET#29]
var transactions = await tonclient.GetTransactions(address: address, limit: 1, hash: transactionId, archival: false);
this code reurns empty array, and no such test in TonSDK repo to check this mehod.

**Comment by purpleguy99** [comment]
Hello. Thanks for the reporting. We will review this in nearest week. As it will be fixed we will notify and close this issue!

**Comment by Maxim055** [comment]
And if i get transaction and its jetton transaction how can i determine that its jetton transaction(ex. JUSDC), and get transfered amount, source address, dest address and if succeded?

**Comment by purpleguy99** [comment]
> And if i get transaction and its jetton transaction how can i determine that its jetton transaction(ex. JUSDC), and get transfered amount, source address, dest address and if succeded?

I think now, it doesnt exists any NFT and Jetton SDK tools. We can add this feature in nearest future, if it will topped by our users. At the moment, you can parse transaction payload data using cellslice and read the data according to TL-B Schemes.
