### ISSUE TITLE
wallet v4

### ISSUE THREAD

**Issue by evilfenggg** [continuation-team/TonSdk.NET#60]
WalletV4 wallet = new TonSdk.Contracts.Wallet.WalletV4(new TonSdk.Contracts.Wallet.WalletV4Options { PublicKey = mnemonic.Keys.PublicKey! });
it's  doesn't work. with transfer

  ExternalInMessage message = wallet.CreateTransferMessage(new[]
    {
    new WalletTransfer
    {
        Message = new InternalMessage(new()
        {
            Info = new IntMsgInfo(new()
            {
         
                Dest =address,

                Value = new Coins("0"),
                //FwdFee = new Coins("0.000000002"),
                //IhrFee= new Coins("0.000000002"),
            }),
             //StateInit=wallet.StateInit,
           Body = new CellBuilder().StoreUInt(0, 520).StoreString(d).Build()
     
    }),

**Comment by purpleguy99** [comment]
Hello. Please provide more information to solve this issue.
