### ISSUE TITLE
Jetton wallet Balance return negative amount

### ISSUE THREAD

**Issue by Maxim055** [continuation-team/TonSdk.NET#61]
Hello, 
Iam using tonecenter jsonRpc API.
By calling Get Balance from jetton wallet it returns negative amount.Here is code sample above,

var jaddressResult = await tonclient.Jetton.GetWalletAddress(new Address(JUSDCTokenContract), new Address(address));
coinsBalanceResult = await tonclient.Jetton.GetBalance(jaddressResult.Value);

Please check it.Thanks.

**Comment by purpleguy99** [comment]
Fixed.
