### ISSUE TITLE
TonConnect - Wallet disconnecting

### ISSUE THREAD

**Issue by Ludwintor** [continuation-team/TonSdk.NET#62]
First issue: Should `Disconnect()` call remove saved key in `RemoteStorage`? I want completely disconnect wallet (like forget about it so `RestoreConnection()` cant reconnect it again. Or I have to save `RemoteStorage` of every connected wallet and manually remove it when wallet disconnect occure?

Second minor issue: Everytime I disconnect wallet I get `Response id 0 doesn't match any request's id ` message in my console but everything fine. It just annoys me

**Comment by purpleguy99** [comment]
> First issue: Should `Disconnect()` call remove saved key in `RemoteStorage`? I want completely disconnect wallet (like forget about it so `RestoreConnection()` cant reconnect it again. Or I have to save `RemoteStorage` of every connected wallet and manually remove it when wallet disconnect occure?
> 
> Second minor issue: Everytime I disconnect wallet I get `Response id 0 doesn't match any request's id ` message in my console but everything fine. It just annoys me

Hello. first issue will be checked. About the second issue, its depends on wallet responses.
We tested it too, and got same warnings. Its depending on specified wallet

**Comment by Ludwintor** [comment]
> > First issue: Should `Disconnect()` call remove saved key in `RemoteStorage`? I want completely disconnect wallet (like forget about it so `RestoreConnection()` cant reconnect it again. Or I have to save `RemoteStorage` of every connected wallet and manually remove it when wallet disconnect occure?
> > Second minor issue: Everytime I disconnect wallet I get `Response id 0 doesn't match any request's id ` message in my console but everything fine. It just annoys me
> 
> Hello. first issue will be checked. About the second issue, its depends on wallet responses. We tested it too, and got same warnings. Its depending on specified wallet

Found out problem why disconnect doesn't remove connection from storage - `Disconnect()` in `BridgeProvider` awaits `SendRequest()` infinitely and never return from it because, as I understand, gateway doesn't answer with any data so we await `resolve.Task` in `BridgeProvider.SendRequest()` until it timeout so we never call `RemoveSession()`

**Comment by purpleguy99** [comment]
> > > First issue: Should `Disconnect()` call remove saved key in `RemoteStorage`? I want completely disconnect wallet (like forget about it so `RestoreConnection()` cant reconnect it again. Or I have to save `RemoteStorage` of every connected wallet and manually remove it when wallet disconnect occure?
> > > Second minor issue: Everytime I disconnect wallet I get `Response id 0 doesn't match any request's id ` message in my console but everything fine. It just annoys me
> > 
> > 
> > Hello. first issue will be checked. About the second issue, its depends on wallet responses. We tested it too, and got same warnings. Its depending on specified wallet
> 
> Found out problem why disconnect doesn't remove connection from storage - `Disconnect()` in `BridgeProvider` awaits `SendRequest()` infinitely and never return from it because, as I understand, gateway doesn't answer with any data so we await `resolve.Task` in `BridgeProvider.SendRequest()` until it timeout so we never call `RemoveSession()`

You can make Pull Request with changes, we will apply them.

**Comment by a2kas** [comment]
i has been solved? because with newest version i still have this issue

**Comment by petriashev** [comment]
The same here

**Comment by a2kas** [comment]
I fixed it in https://github.com/continuation-team/TonSdk.NET/pull/137

**Comment by purpleguy99** [comment]
https://github.com/continuation-team/TonSdk.NET/pull/140
