### ISSUE TITLE
TonConnect crashes application on user rejected connection

### ISSUE THREAD

**Issue by Ludwintor** [continuation-team/TonSdk.NET#63]
Sorry for inconvenience but what that hell is wrong with this TonConnect sdk? Why `OnWalletConnectError` in `TonConnect` throws exceptions that are impossible to catch and handle because this method called from arbitrary task that is not awaited when we receive payload? User reject to connect just lead to application crash and you cant do anything with it. Does this sdk even was tested?

**Comment by Ludwintor** [comment]
Why do we even throw these exceptions in that method?? Method already propogated error message to `StatusChangeErrorsHandler`s, what purpose of throwing additional exception that even impossible to handle?

**Comment by purpleguy99** [comment]
> Sorry for inconvenience but what that hell is wrong with this TonConnect sdk? Why `OnWalletConnectError` in `TonConnect` throws exceptions that are impossible to catch and handle because this method called from arbitrary task that is not awaited when we receive payload? User reject to connect just lead to application crash and you cant do anything with it. Does this sdk even was tested?

No this SDK, wasnt tested.
