### ISSUE TITLE
error :LITE_SERVER_UNKNOWN 

### ISSUE THREAD

**Issue by MassoudKargar** [continuation-team/TonSdk.NET#66]
i test this code but code return this error :
Received error: {"ok":false,"error":"LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by transaction 567F1D4BCB17CE7440806854F3DB31A986229B46C73EFE0835F80B9E4CAC5258:\nexitcode=9, steps=8, gas_used=0\nVM Log (truncated):\n...execute SETCP 0\nexecute DICTPUSHCONST 19 (xC_,1)\nexecute DICTIGETJMPZ\nexecute PUSHPOW2 9\nexecute LDSLICEX\nexecute DUP\nexecute LDU 32\nhandling exception code 9: cell underflow\ndefault exception handler, terminating vm with exit code 9\n","code":500}
i dont know what happend.

this my code

try
{
TonClient tonclient = new(new TonClientParameters
{
Endpoint = "https://toncenter.com/api/v2/jsonRPC",
ApiKey = "...",
});
var destination = new Address("UQBWfx1LyxfOdECAaFTz2zGphiKbRsc-_gg1-AueTKxSWPZ9");

var mnemonic = new Mnemonic();

WalletV4 walletV4 = new WalletV4(new WalletV4Options() { PublicKey = mnemonic.Keys.PublicKey! });

// Create a transfer message for the wallet
ExternalInMessage message = walletV4.CreateTransferMessage(new[]
{
    new WalletTransfer
    {
        Message = new ExternalInMessage(new()
        {
            Info = new ExtInMsgInfo(new()
            {
                Dest = destination,
                ImportFee = new Coins("0.013"),
                Src = walletV4.Address
            }),
            Body = new Message(destination, new Coins("0.5")).Payload,
            StateInit = new StateInit(new StateInitOptions()),
        }),
        Mode = 1
    }
}, 0).Sign(mnemonic.Keys.PrivateKey, true);

await tonclient.SendBoc(message.Cell!);
}
catch (Exception e)
{
Console.WriteLine(e);
throw;
}

**Comment by Ludwintor** [comment]
same issue on simple transfer, even tried my own toncenter client with api v3 - probably issue with boc serialization in this sdk

**Comment by Ludwintor** [comment]
solved this issue, you should use sign trascation with second argument set to false `Sign(mnemonic.Keys.PrivateKey, false)`

as I understand walletv2 reads signature from ref, when v3 and v4 reads directly 512 bits, setting second argument to `true` causes to store signature to ref and because of that we getting cell underflow

**Comment by purpleguy99** [comment]
guide about using wallet v3 v4 contracts - https://docs.tonsdk.net/user-manual/contracts/wallet/wallet-v3-v4
